### ISSUE TITLE
No [M/H] range variable

### ISSUE THREAD

**Issue by tombickleastro** [suarezgenaro/seda#13]
The model options has variables for teff, logg and R ranges, but is missing a variable for metallicity range.

**Comment by suarezgenaro** [comment]
Thanks for opening this issue. I had this in my to-do list. I implemented it, so the code allows now to define a range for any free parameter in the models. See more details here on how to set the ranges: https://seda.readthedocs.io/en/latest/api.html#seda.input_parameters.ModelOptions
