### ISSUE TITLE
Store convolved grids

### ISSUE THREAD

**Issue by tombickleastro** [suarezgenaro/seda#14]
The main time consumption comes from convolving the grid spectra. It might be worth adding an option for users to be able to store convolved grids to their disk space, so that bulk target spectra of the same resolution can be done quicker.

**Comment by suarezgenaro** [comment]
This is a great idea to save lots of time when modeling spectra with the same resolution as the convolved ones. I have implemented this. 

When defining model options with ModelOptions, you can set the parameter path_save_spectra_conv with a path to save the convolved spectra (read https://seda.readthedocs.io/en/latest/api.html#seda.input_parameters.ModelOptions). To reused the saved convolved spectra next time you run the code: i) set skip_convolution=True in ModelOptions to avoid the model spectra convolution and ii) model_dir in ModelOptions should correspond to the directory with the convolved spectra. 

I hope this helps.
