### ISSUE TITLE
Abs flux

### ISSUE THREAD

**Issue by tombickleastro** [suarezgenaro/seda#15]
It would be great to have an option to convert a spectrum to absolute flux based on a distance input, and have the converted file as an output.

**Comment by tombickleastro** [comment]
Observed preferably. I know sedkit is supposed to be able to do it, but for some reason its always given me issues w/ healpy when attempting to download it.

**Comment by suarezgenaro** [comment]
I added the function seda.app_to_abs_flux (in utils.py) to convert apparent fluxes into absolute ones and propagate flux and distance uncertainties, if provided. See more details at:
https://seda.readthedocs.io/en/latest/api.html#seda.utils.app_to_abs_flux
