### ISSUE TITLE
output file name

### ISSUE THREAD

**Issue by tombickleastro** [suarezgenaro/seda#16]
It would be nice to have a way to specify within the code what the name of the output file is. At the moment, they're all coming out with the same name (e.g. SED_Sonora_Diamondback_chi2.pdf)

**Comment by suarezgenaro** [comment]
I have added two extra optional parameters to the plotting functions:  'save' to indicate if the plot will be saved or not and 'out_file' to provide the file name. Look at Parameters for seda.plot_chi2_fit as an example:
https://seda.readthedocs.io/en/latest/api.html#seda.plots.plot_chi2_fit
