### ISSUE TITLE
xarray version issue

### ISSUE THREAD

**Issue by rothermichaustin** [suarezgenaro/seda#8]
The 2022.11.0 version of xarray gives no errors, but will fail to import in SEDA using the 2024.10.0 version.

**Comment by suarezgenaro** [comment]
I upgraded my xarray to the most recent version 2024.7.0 available for python 3.9 and the code works fine, but the following warning may appear 
UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed). 
In this case, we can just upgrade pandas and/or bottleneck used by xarray doing:
pip install pandas -U
pip install bottleneck -U

I will check what the error is for xarray 2024.10.0 version, which is available only for python>=3.10.

**Comment by kelle** [comment]
(Side comment: Since this is a new package, it really should be compatible with 3.11 and higher. We shouldn't be worried about 3.9. Maybe we need a new issue to address python version.)

**Comment by suarezgenaro** [comment]
Good point, Kelle. I will test the code in Python >=3.11. Do you mind opening a new issue on this?

**Comment by suarezgenaro** [comment]
I have verified the code works well in Python 3.11 with xarray 2024.10.0.
